export const App = {
    BaseUrl: 'https://stackumbrella.com',
    BaseUrl2: 'https://stackumbrella.in',
    BaseUrl3: 'https://www.agnitotoday.com',
    PostFix: '/wp-json/wp/v2',
    PostCategory: '&categories=',
    PostCategoryId: '?categories=',
    NavCategoryPerPage: '/categories?per_page=100',
    PostPage: '/posts?page=',
    Embd: '&_embed',
    _Embd: '?_embed',
    WebStory: '/web-stories',
    TokenUploadApi: "/devicetocke.php?device_token=",
    Posts: '/posts/',
    PerPage : '&per_page=',
}
export const icons = {
    Bollywood: "../assets/icon/navIcon/bollywood.svg",
    business: "../assets/icon/navIcon/business.svg",
    career: "../assets/icon/navIcon/career.svg",
    coronavirus: "../assets/icon/navIcon/coronavirus.svg",
    fashion: "../assets/icon/navIcon/fashion.svg",
    fire: "../assets/icon/navIcon/fire.svg",
    food: "../assets/icon/navIcon/food.svg",
    government: "../assets/icon/navIcon/government.svg",
    heath: "../assets/icon/navIcon/heath.svg",
    hollywood: "../assets/icon/navIcon/hollywood.svg",
    Informative: "../assets/icon/navIcon/Informative.svg",
    Inspiration: "../assets/icon/navIcon/Inspiration.svg",
    lifetyle: "../assets/icon/navIcon/lifetyle.svg",
    news: "../assets/icon/navIcon/news.svg",
    politics: "../assets/icon/navIcon/politics.svg",
    relation: "../assets/icon/navIcon/relation.svg",
    Sports: "../assets/icon/navIcon/Sports.svg",
    tech: "../assets/icon/navIcon/tech.svg",
    travel: "../assets/icon/navIcon/travel.svg",
    uncategorized: "../assets/icon/navIcon/uncategorized.svg",
    video: "../assets/icon/navIcon/video.svg",
    viral: "../assets/icon/navIcon/viral.svg",
    webseries: "../assets/icon/navIcon/webseries.svg",
    webstories: "../assets/icon/navIcon/webstories.svg",

}